package io.ib67.prts.project;

import io.quarkus.hibernate.orm.panache.PanacheEntityBase;
import io.quarkus.panache.common.Sort;
import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.FetchType;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.Index;
import jakarta.persistence.JoinColumn;
import jakarta.persistence.ManyToOne;
import jakarta.persistence.Table;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;
import lombok.ToString;
import org.hibernate.annotations.CreationTimestamp;
import org.hibernate.annotations.OnDelete;
import org.hibernate.annotations.OnDeleteAction;

import java.time.Instant;
import java.util.List;
import java.util.UUID;

/**
 * A single log line emitted by a job. High volume, which is why it is keyed by a cheap identity
 * bigint rather than a UUID.
 */
@Entity
@Table(name = "job_log", indexes = @Index(name = "idx_job_log", columnList = "job_id, created_at"))
@Getter
@Setter
@NoArgsConstructor
@AllArgsConstructor
@Builder
@ToString
public class JobLog extends PanacheEntityBase {

    /**
     * import.sql declares {@code GENERATED ALWAYS}; Hibernate's PostgreSQL DDL emits
     * {@code GENERATED BY DEFAULT}. Behaviour is the same here because identity inserts never send
     * the column.
     */
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Column(name = "id", nullable = false, updatable = false)
    private Long id;

    @ManyToOne(fetch = FetchType.LAZY, optional = false)
    @JoinColumn(name = "job_id", nullable = false, updatable = false)
    @OnDelete(action = OnDeleteAction.CASCADE)
    @ToString.Exclude
    private Job job;

    @CreationTimestamp
    @Column(name = "created_at", nullable = false, updatable = false)
    private Instant createdAt;

    @Column(name = "topic", columnDefinition = "varchar")
    private String topic;

    @Column(name = "message", columnDefinition = "text")
    private String message;

    /**
     * Normalized on write, so nothing new lands here as null. Rows written before the column became
     * {@code NOT NULL} may still hold null, which means "no error".
     */
    @Column(name = "error", nullable = false)
    private Boolean error;

    /**
     * Served straight out of {@code idx_job_log}. The id breaks ties: lines written in one
     * transaction share a timestamp, and a paged read needs a total order.
     */
    private static Sort chronological() {
        return Sort.by("createdAt").and("id");
    }

    /** {@code range} is inclusive on both ends, hence {@code offset + length - 1}. */
    public static List<JobLog> listByJob(UUID jobId, int offset, int length) {
        return find("job.id", chronological(), jobId).range(offset, offset + length - 1).list();
    }
}
