package io.ib67.prts.project;

import io.quarkus.hibernate.orm.panache.PanacheEntityBase;
import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.Id;
import jakarta.persistence.Table;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;
import lombok.ToString;
import org.hibernate.annotations.UuidGenerator;

import java.util.UUID;

/**
 * A project, the unit that jobs and memberships hang off.
 */
@Entity
@Table(name = "project")
@Getter
@Setter
@NoArgsConstructor
@AllArgsConstructor
@Builder
@ToString
public class Project extends PanacheEntityBase {

    /**
     * Generated by the application rather than the database. {@code @UuidGenerator} is itself an
     * {@code @IdGeneratorType}, so no companion {@code @GeneratedValue} is needed.
     */
    @Id
    @UuidGenerator(style = UuidGenerator.Style.VERSION_7)
    @Column(name = "id", nullable = false, updatable = false)
    private UUID id;

    /** {@code columnDefinition} keeps import.sql's unbounded varchar; Hibernate would emit varchar(255). */
    @Column(name = "name", nullable = false, columnDefinition = "varchar")
    private String name;
}
