-- CREATE TABLE "project"
-- (
--     id   uuid    NOT NULL PRIMARY KEY, -- auto generated uuid v7
--     name varchar NOT NULL
-- );
--
-- CREATE TABLE prts_user
-- (
--     id         uuid        NOT NULL PRIMARY KEY,
--     name       varchar     NOT NULL,
--     email      varchar     NOT NULL,
--     created_at timestamptz NOT NULL
-- );
--
-- CREATE TABLE "job"
-- (
--     id             uuid        NOT NULL PRIMARY KEY, -- auto generated uuid v7
--     project_id     uuid        NOT NULL,
--     created_at     timestamptz NOT NULL,
--     completed_at   timestamptz,
--     state          varchar     NOT NULL DEFAULT 'PENDING',
--     worker         uuid,                             -- set once a worker takes the job
--     spec           jsonb,
--     resource_class varchar     NOT NULL,              -- resolved at create time; a rerun names this one
--     resource_class_project uuid NOT NULL,
--     template_id    uuid,                              -- with create_override, what a rerun replays
--     create_override jsonb,
--     FOREIGN KEY (project_id)
--         REFERENCES project (id)
--         ON DELETE CASCADE,
--     FOREIGN KEY (resource_class, resource_class_project)
--         REFERENCES resource_class (name, project_id),
--     CHECK (state IN ('PENDING', 'RUNNING', 'FAILED', 'SUCCESS', 'CANCELLED')),
--     CHECK (
--         ((state = 'PENDING' OR state = 'RUNNING') AND completed_at IS NULL)
--             OR
--         (state IN ('SUCCESS', 'FAILED', 'CANCELLED') AND completed_at IS NOT NULL)
--         )
-- );
--
-- CREATE INDEX idx_job_project_id ON job (project_id);
--
-- -- Holder of JobSpec.lock: two jobs naming the same lock never run at once. Scoped per project,
-- -- held from dispatch until the job is terminal.
-- CREATE TABLE "job_lock"
-- (
--     project_id  uuid        NOT NULL,
--     name        varchar     NOT NULL,
--     job_id      uuid        NOT NULL UNIQUE, -- a spec carries one lock, so one per job
--     acquired_at timestamptz NOT NULL,
--     PRIMARY KEY (project_id, name),
--     FOREIGN KEY (project_id) REFERENCES project (id) ON DELETE CASCADE,
--     FOREIGN KEY (job_id) REFERENCES job (id) ON DELETE CASCADE
-- );
--
-- CREATE TABLE "artifact"
-- (
--     id         uuid    NOT NULL PRIMARY KEY, -- auto generated uuid v7
--     name       varchar NOT NULL,
--     object_key text    NOT NULL,
--     size_bytes bigint  NOT NULL,
--     job_id     uuid    NOT NULL,
--     FOREIGN KEY (job_id) REFERENCES job (id) ON DELETE CASCADE
-- );
--
-- CREATE INDEX idx_artifact_job_id
--     ON artifact (job_id);
--
-- CREATE TABLE "job_log"
-- (
--     id         bigint      NOT NULL
--         GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
--     job_id     uuid        NOT NULL,
--     created_at timestamptz NOT NULL,
--     topic      varchar,
--     message    text,
--     error      boolean     NOT NULL,
--     FOREIGN KEY (job_id) REFERENCES job (id) ON DELETE CASCADE
-- );
--
-- CREATE INDEX idx_job_log
--     ON job_log (job_id, created_at);
--
-- CREATE TABLE "user_to_project"
-- (
--     user_id    uuid NOT NULL,
--     project_id uuid NOT NULL,
--     -- role: OWNER, MEMBER, VIEWER, NONE. Hibernate derives both the smallint and the CHECK from
--     -- the ordinal enum, so this is what it emits rather than a hand-written constraint.
--     role       smallint NOT NULL CHECK (role >= 0 AND role <= 3),
--     PRIMARY KEY (user_id, project_id),
--     FOREIGN KEY (user_id) REFERENCES prts_user (id) ON DELETE CASCADE,
--     FOREIGN KEY (project_id) REFERENCES project (id) ON DELETE CASCADE
-- );
--
-- CREATE TABLE "oauth_identity"
-- (
--     issuer  varchar NOT NULL,
--     subject varchar NOT NULL,
--     user_id uuid    NOT NULL
--         REFERENCES prts_user (id)
--             ON DELETE CASCADE,
--     PRIMARY KEY (issuer, subject)
-- );
--
-- CREATE TABLE "resource_class"
-- (
--     name         varchar NOT NULL,
--     -- The project that defines it. Part of the key, so "global" is the reserved all-zero id
--     -- rather than null; a project's own row shadows a global one of the same name.
--     project_id   uuid    NOT NULL,
--     num_cpus     int     NOT NULL,
--     mem_count    int     NOT NULL,
--     disk_size    int     NOT NULL,
--     PRIMARY KEY (name, project_id)
-- );
--
-- CREATE TABLE "job_spec_template"
-- (
--     id             uuid    NOT NULL PRIMARY KEY,
--     name           varchar NOT NULL,
--     spec           jsonb   NOT NULL,
--     resource_class varchar,
--     resource_class_project uuid, -- must be the global scope when project_id is null
--     project_id     uuid,   -- null: a global template every project may use
--     FOREIGN KEY (resource_class, resource_class_project)
--         REFERENCES resource_class (name, project_id),
--     FOREIGN KEY (project_id) REFERENCES project (id)
-- );
--
-- CREATE INDEX idx_job_spec_template_project_id ON job_spec_template (project_id);
--
-- CREATE TABLE "registeredWorker"
-- (
--     id   uuid    NOT NULL PRIMARY KEY,
--     name varchar NOT NULL
-- );
--
-- CREATE TABLE "worker_volume"
-- (
--     id         uuid        NOT NULL PRIMARY KEY,
--     name       varchar     NOT NULL,
--     created_at timestamptz NOT NULL,
--     worker_id  uuid        NOT NULL,
--     project_id uuid        NOT NULL,
--     length     bigint      NOT NULL,
--     used       bigint      NOT NULL,
--     FOREIGN KEY (worker_id) REFERENCES registeredWorker (id),
--     FOREIGN KEY (project_id) REFERENCES project (id),
--     CHECK (length >= 0 AND used >= 0 AND used <= length)
-- );
--
-- CREATE INDEX idx_worker_volume_worker_id ON worker_volume (worker_id);
-- CREATE INDEX idx_worker_volume_project_id ON worker_volume (project_id);
--
-- CREATE TABLE "project_secret"
-- (
--     project_id  uuid        NOT NULL,
--     name        varchar     NOT NULL,              -- unique per project, and the only handle
--     description varchar,                           -- what the name is for; never the value
--     -- AES-GCM under one of secret.keys: '<format>:<keyId>:<base64 of iv || ciphertext || tag>'.
--     -- The key id is in the row so a key can be rotated without a schema change; format and id are
--     -- authenticated along with (project_id, name), so a row cannot be moved or relabelled.
--     cipher_text varchar     NOT NULL,
--     created_at  timestamptz NOT NULL,
--     PRIMARY KEY (project_id, name),
--     FOREIGN KEY (project_id) REFERENCES project (id) ON DELETE CASCADE
-- );
